# github workflow
name: automatic-release

on:
  push:
    branches:
    - develop
    - master
    - main

  pull_request:
    branches:
    - main
    - master
    - develop

env:
  IDF_VERSION: v3.2

jobs:

  build-all:
    runs-on: ubuntu-latest
    env:
      OVERRIDE: nothing
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tag Version
      run: |
        DATE="$(date +%Y%m%d)"
        HASH="$(git describe --long --tags --dirty --always)"
        echo "${DATE}-${HASH}" | tee VERSION
    - name: Docker Build & Push
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: pvtmert/esp32-at-ppp
        add_git_labels: true
        tag_with_ref: true
        tag_with_sha: true
        always_pull: true
        dockerfile: Dockerfile
        tags: latest
        push: true
        path: .
    - name: Run container
      run: docker run
        --rm=false
        --restart=no
        --name="${GITHUB_ACTOR}_${GITHUB_ACTION}_${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ID}"
        ghcr.io/pvtmert/esp32-at-ppp
    - name: Copy Files Out
      run: docker cp "$(docker ps -qa | head -1):/home/output" "./binaries"
    - name: Copy Version into Output Directory
      run: cp -v VERSION ./binaries/
    - name: Compress Artifacts
      run: tar -cav -C ./binaries -f artifacts.txz .
    - name: Upload Archive
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build.artifacts
        path: ./artifacts.txz
